# Python
## 13 September 2023

## Numpy

In [23]:
list = [1,3,5,6]
print(type(list))

<class 'list'>


In [24]:
import numpy as np
arr = np.array(list)
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
arr2 = np.array([l1,l2])
print(arr2[1,2])
print(arr2[0,1])
print(arr2[1,4])

8
2
10


In [31]:
arr2[0,1:3]

array([2, 3])

In [32]:

arr2[1:5]

array([[ 6,  7,  8,  9, 10]])

In [30]:

arr2[1::2]

array([[ 6,  7,  8,  9, 10]])

In [40]:
aaa = np.array([l1,l2])
print(aaa)
a = aaa.reshape(-1)
print(a)
aa=a.reshape(5,2)
print(aa)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
