<div style="border: 1px solid black; padding:8px;">
    <h1> <center> PC-503 Programming Lab </center> </h1>
    <h3> <center> Assignment 4 </center> </h3>
    <div style="display: flex; justify-content: space-between; margin-bottom:12px;">
    <span style="padding:0px 16px; font-size:18px;">
        Nirmal Shah
    </span>
    <span style="padding:0px 16px; font-size:18px;">
        202311043
    </span>
    </div>
</div>


### Q1. Implement a custom exception named "CustomOutOfRangeError." Write a Python program that asks the user to enter an integer within a specified range (e.g., 10 to 50). If the input is outside this range, raise the "CustomOutOfRangeError" with a meaningful error message. Handle this exception and ask the user for input again until a valid input is provided.

In [3]:
class CustomOutOfRangeError(Exception):
    def __init__(self, message="Input is out of specified range"):
        self.message = message
        super().__init__(self.message)

def get_valid_input(min_range, max_range):
    while True:
        try:
            user_input = int(input(f"Enter an integer between {min_range} and {max_range}: "))
            if min_range <= user_input <= max_range:
                return user_input
            else:
                raise CustomOutOfRangeError()
        except CustomOutOfRangeError as e:
            print(e)
        except ValueError:
            print("Invalid input. Please enter an integer.")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

In [6]:
# Example usage
min_range = 10
max_range = 50

user_input = get_valid_input(min_range, max_range)
print(f"You entered: {user_input}")

Input is out of specified range
Input is out of specified range
You entered: 45


### Q2. Write a Python program that reads data from a CSV file. Implement exception handling to manage potential errors such as file not found,  nvalid data format, or missing columns. Create a custom exception "CSVDataError" to handle issues related to data format. Display appropriate  error messages for different exceptions.

In [15]:
from tabulate import tabulate

class CSVDataError(Exception):
    def __init__(self, message="CSV data error"):
        self.message = message
        super().__init__(self.message)

def read_csv_file(file_path):
    try:
        with open(file_path, 'r') as file:
            header = file.readline().strip().split(',')
            data = []
            for line in file:
                values = line.strip().split(',')
                if len(values) != len(header):
                    raise CSVDataError("Number of columns in the CSV data is inconsistent.")
                data.append(values)
            return header, data
    except FileNotFoundError:
        raise FileNotFoundError(f"File '{file_path}' not found.")
    except CSVDataError as e:
        raise e
    except Exception as e:
        raise Exception(f"An unexpected error occurred: {e}")


In [16]:

file_path = 'temfp.csv'
try:
    header, data = read_csv_file(file_path)
    table = tabulate(data, header, tablefmt="grid")
    print(table)
except FileNotFoundError as e:
    print(e)
except CSVDataError as e:
    print(f"CSV Data Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

File 'temfp.csv' not found.


In [17]:

file_path = 'temp.csv'
try:
    header, data = read_csv_file(file_path)
    table = tabulate(data, header, tablefmt="grid")
    print(table)
except FileNotFoundError as e:
    print(e)
except CSVDataError as e:
    print(f"CSV Data Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

+--------+--------+--------+
| col1   | col2   | col3   |
+========+========+========+
| d1     | d2     | d3     |
+--------+--------+--------+
| a1     | a2     | a3     |
+--------+--------+--------+


In [18]:

file_path = 'temp2.csv'
try:
    header, data = read_csv_file(file_path)
    table = tabulate(data, header, tablefmt="grid")
    print(table)
except FileNotFoundError as e:
    print(e)
except CSVDataError as e:
    print(f"CSV Data Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

CSV Data Error: Number of columns in the CSV data is inconsistent.


### Q3. Create a Python module that defines a function to calculate the nth Fibonacci number. Import this module into another script and use the function to calculate the Fibonacci sequence for the first 15 numbers. Display the results.

In [ ]:
### Fibonacci.py File
# def calculate_fibonacci(n):
#     if n <= 0:
#         return "Invalid input"
#     elif n == 1:
#         return 0
#     elif n == 2:
#         return 1
#     else:
#         a, b = 0, 1
#         for _ in range(3, n + 1):
#             a, b = b, a + b
#         return b

In [21]:
import fibonacci

print("Fibonacci sequence for the first 15 numbers:")

fibonacci_sequence = [fibonacci.calculate_fibonacci(n) for n in range(1, 16)]
print(fibonacci_sequence)


Fibonacci sequence for the first 15 numbers:
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]


### Q4. Develop a Python module that provides functionalities for matrix operations, including addition, subtraction, and multiplication using NumPy. Use this module to perform matrix multiplication on two randomly generated matrices.

In [22]:
### Matrix.py File

# import numpy as np

# def generate_matrix(row, col):
#     return np.random.randint(1, 10, size=(row, col))

# def add_matrices(matrix1, matrix2):
#     return np.add(matrix1, matrix2)

# def subtract_matrices(matrix1, matrix2):
#     return np.subtract(matrix1, matrix2)

# def multiply_matrices(matrix1, matrix2):
#     return np.matmul(matrix1, matrix2)

In [29]:
import matrix as mx

M1 = mx.generate_matrix(4,3)
M2 = mx.generate_matrix(3,2)
M3 = mx.generate_matrix(4,3)

add = mx.add_matrices(M1, M3)
sub = mx.subtract_matrices(M1, M3)
mul = mx.multiply_matrices(M1, M2)



In [31]:
print("M1 = \n",M1)
print("")
print("M2 = \n",M2)
print("")
print("M3 = \n",M3)
print("")

M1 = 
 [[9 8 2]
 [8 4 5]
 [1 7 8]
 [8 5 5]]

M2 = 
 [[6 4]
 [1 4]
 [3 5]]

M3 = 
 [[6 3 2]
 [7 4 9]
 [2 8 3]
 [9 9 8]]



In [33]:
print("Addition M1 + M3 = \n", add)
print()
print("Subraction M1 - M3 = \n", sub)
print()
print("Multiplication M1 x M2 = \n", mul)
print()

Addition M1 + M3 = 
 [[15 11  4]
 [15  8 14]
 [ 3 15 11]
 [17 14 13]]

Subraction M1 - M3 = 
 [[ 3  5  0]
 [ 1  0 -4]
 [-1 -1  5]
 [-1 -4 -3]]

Multiplication M1 x M2 = 
 [[68 78]
 [67 73]
 [37 72]
 [68 77]]



### Q5. Write a Python program that generates a 10x10 numpy array with random integers between 1 and 100. Find and display the indices of the top 5 maximum values in the array.

In [43]:
import numpy as np

random_array = np.random.randint(1, 101, size=(10, 10))

print("Generated 10x10 NumPy Array:")
print(random_array)

top_indices = np.unravel_index(np.argsort(random_array, axis=None)[-5:], random_array.shape)

print("\nIndices of the Top 5 Maximum Values:\n")
for i in range(4,-1,-1):
    print(f"Top {5-i} value: {random_array[top_indices[0][i], top_indices[1][i]]} at index {top_indices[0][i]}, {top_indices[1][i]}")


Generated 10x10 NumPy Array:
[[ 25  49  91  74  21  79  68  27  44   4]
 [ 88  30 100  34  84  69  95   2  32  73]
 [ 57  21  17  49  63  16  24  45  13  72]
 [ 15  11  92  60  89  29  34  48  98  34]
 [ 11  42  55  11  67  14  76  70  43  25]
 [ 60  24  37  58  90  85  22  71  61  46]
 [ 34  68  84  47  53  80  69  88  61  28]
 [ 81  14  82  81  82  48  39  28  28  32]
 [ 51  99  91  55  33  63  75  83   8   2]
 [ 80 100  68  11  28  98  99  92  79  59]]

Indices of the Top 5 Maximum Values:

Top 1 value: 100 at index 9, 1
Top 2 value: 100 at index 1, 2
Top 3 value: 99 at index 9, 6
Top 4 value: 99 at index 8, 1
Top 5 value: 98 at index 9, 5
